### ISSUE TITLE
Missing file and functions

### ISSUE THREAD

**Issue by mct10** [facebookresearch/stopes#59]
Hi,

I am trying to use stopes for speech mining, and I think there are files and functions missing.

- The `speech_units.py` file is missing, which is imported [here](https://github.com/facebookresearch/stopes/blob/main/stopes/modules/preprocess/mining_speech_encoder.py#L16)
Also, the `parallel_audio_read` function does not exist.

- In `wav2vec_laser_speech_encoder.py`, there is no `AudioDataset` class. This is imported [here](https://github.com/facebookresearch/stopes/blob/main/stopes/modules/preprocess/mining_speech_encoder.py#L125).

Could you take a look at this? Thank you in advance.

**Comment by antoine-tran** [comment]
HI @mct10, sorry for the late reply. Just a heads-up that last week we release a new version of stopes (2.1.0), and the issues should be resolved now

**Comment by mct10** [comment]
Thank you so much!
